version: '3.9'

volumes:
  db_data:
  rabbitmq_data:

services:
  db:
    image: rethinkdb:2
    hostname: db
    volumes:
      - db_data:/data
    #ports:
      # - "28080:8080/tcp"  # Web
      # - "28015:28015/tcp" # Driver
      # - "29015:29015/tcp" # Cluster
  
  # messaging:
  #   image: rabbitmq:3-management
  #   hostname: messaging
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq/
    
  web:
    build:
      context: ./web
    environment:
      PANYAPATI_WEB_HOST: localhost
    ports:
      - "8443:443/tcp"
    depends_on:
      - db
      - ingestion
      - display

  ingestion:
    build:
      context: ./apps/ingestion
    environment:
      BINANCE_API_KEY: ${BINANCE_API_KEY:?}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET:?}
    depends_on:
      - db

  display:
    build:
      context: ./apps/display
    depends_on:
      - db

  # jumphost:
  #   image: ubuntu
  #   command: sleep infinity
